### ISSUE TITLE
播放器可调节的功能好少

### ISSUE THREAD

**Issue by zymshirley** [MCDFsteve/NipaPlay#12]
播放器可调节的功能好少呀
我的用的是emby的外链，除了声音和进度和字幕可以调，其他什么都调不了，比如倍速、明暗之类的

**Comment by MCDFsteve** [comment]
目前只做了我常用的功能，你说的这些，后面我会更新

**Comment by MCDFsteve** [comment]
倍速播放和视频亮度功能已更新。--1.6.0
