### ISSUE TITLE
本项目将会尝试通过Flutter重写。以拥有更好的视频兼容性和更高的性能以及更多平台

### ISSUE THREAD

**Issue by MCDFsteve** [MCDFsteve/NipaPlay#6]
计划重写之后同时拥有 Android IOS macOS Linux Windows平台

**Comment by yukminnie** [comment]
> 计划重写之后同时拥有 Android IOS macOS Linux Windows平台

建议增加媒体库视频播放时, 检索目录下同名弹幕自动加载的功能( Ĭ ^ Ĭ )

**Comment by MCDFsteve** [comment]
会考虑加入

**Comment by MCDFsteve** [comment]
> > 计划重写之后同时拥有 Android IOS macOS Linux Windows平台
> 
> 建议增加媒体库视频播放时, 检索目录下同名弹幕自动加载的功能( Ĭ ^ Ĭ )

功能已更新，并且不需要同名，在一个文件夹下就行
